name: Pull Request Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'ubuntu-22.04'
        type: choice
        options:
        - ubuntu-22.04
        - windows-2022
        - macos-14
      debug:
        description: 'Build in debug mode'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        # Only use matrix for automatic builds (PR/push), not for manual dispatch
        platform: ${{ github.event_name == 'workflow_dispatch' && fromJSON('[""]') || fromJSON('["ubuntu-22.04", "windows-2022", "macos-14"]') }}
        exclude:
          # Exclude empty platform when using manual dispatch
          - platform: ""
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) == 'macos-14' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup FFmpeg (macOS)
        if: (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) == 'macos-14'
        uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: 71

      - name: Setup FFmpeg (Windows/Linux)
        if: (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) != 'macos-14' && (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) != ''
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: 'x64'
          linking-type: static

      - name: Install dependencies (ubuntu only)
        if: (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgtk-3-dev libxdo-dev libxrandr-dev libxcb-randr0-dev pkg-config
          # Install FFmpeg development libraries for Rust compilation
          sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev
          # Verify FFmpeg installation
          pkg-config --modversion libavutil || echo "FFmpeg pkg-config not found"

      - name: Install dependencies (macOS only)
        if: (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) == 'macos-14'
        run: |
          # Install pkg-config and FFmpeg for development headers
          brew install pkg-config ffmpeg
          
          # Set up environment for cross-compilation
          echo "MACOSX_DEPLOYMENT_TARGET=10.13" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_SYSTEM_LIBS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1" >> $GITHUB_ENV
          
          # Set PKG_CONFIG_PATH to include both Homebrew and AnimMouse FFmpeg
          echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          
          # Verify FFmpeg installation
          pkg-config --modversion libavutil || echo "libavutil not found via pkg-config"
          pkg-config --libs libavutil || echo "libavutil libs not found"

      - name: Install dependencies (Windows only)
        if: (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) == 'windows-2022'
        run: |
          # Install vcpkg for FFmpeg development libraries
          git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe integrate install
          # Install FFmpeg with all required components
          .\vcpkg.exe install ffmpeg[core,avcodec,avformat,avdevice,avfilter,swresample,swscale]:x64-windows
          # Set environment variables
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
          echo "PKG_CONFIG_PATH=C:\vcpkg\installed\x64-windows\lib\pkgconfig" >> $env:GITHUB_ENV

      - name: Install frontend dependencies
        run: npm ci

      - name: Build the app (Release)
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.debug || github.event_name != 'workflow_dispatch' }}
        env:
          RUSTFLAGS: ${{ env.RUSTFLAGS }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_ALLOW_SYSTEM_LIBS: 1
          PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1
        run: npm run tauri:build

      - name: Build the app (Debug)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
        env:
          RUSTFLAGS: ${{ env.RUSTFLAGS }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_ALLOW_SYSTEM_LIBS: 1
          PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1
        run: npm run tauri:build:debug

      - name: Upload artifacts (Linux)
        if: (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) == 'ubuntu-22.04'
        env:
          RUSTFLAGS: ${{ env.RUSTFLAGS }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact@v4
        with:
          name: clever-kvm-linux
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/clever-kvm

      - name: Upload artifacts (Windows)
        if: (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) == 'windows-2022'
        env:
          RUSTFLAGS: ${{ env.RUSTFLAGS }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact@v4
        with:
          name: clever-kvm-windows
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/clever-kvm.exe

      - name: Upload artifacts (macOS)
        if: (github.event_name == 'workflow_dispatch' && inputs.platform || matrix.platform) == 'macos-14'

        env:
          RUSTFLAGS: ${{ env.RUSTFLAGS }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact@v4
        with:
          name: clever-kvm-macos
          path: |
            src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
            src-tauri/target/universal-apple-darwin/release/bundle/macos/*.app
            src-tauri/target/universal-apple-darwin/release/clever-kvm
